{
    "response": "HTTPConnectionPool(host='172.21.25.95', port=5441): Max retries exceeded with url: /app/otter (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc6d33e9100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
}